# Generated by Django 3.2.14 on 2022-07-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, verbose_name='Идентификатор чата')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описани теста')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Результаты тестирования')),
                ('complete', models.BooleanField(verbose_name='Тест пройден полностью?')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.test', verbose_name='Название теста')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Чей результат')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('serial_number', models.PositiveIntegerField(verbose_name='Номер вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.test', verbose_name='Относиться к тесту...')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('result', models.TextField(blank=True, verbose_name='Текст который добавиться к результату тестирования при выборе этого ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.question', verbose_name='Относиться к вопросу...')),
            ],
        ),
    ]
